source = ~/.config/Zenith/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/Zenith/current/background.jpeg
    blur_passes = 3
    blur_size = 4

    #contrast = 1
    #brightness = 1
    #vibrancy = 0.5
}

label {
    monitor =
    text = $TIME
    font_family = JetBrainsMonoNL Nerd Font
    font_size = 110

    color = $font_color

    position = 0, 150
    halign = center
    valign = center
}

#date and day
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = $font_color
    font_size = 16
    font_family = JetBrainsMonoNL Nerd Font
    position = 0, 62
    halign = center
    valign = center
}

#profile image
#image {
#    monitor =
#    path = /home/golu/.config/Zenith/current/profile-5.png
#    border_color = $outer_colors;
#    border_size = 1
#    size = 180
#
#    rounding = -1
#    rotate = 0
#    reload_time = -1
#    reload cmd =
#    position = 0, 0
#
#    halign = center
#    valign = center
#
#    #contrast = 1
#    #brightness = 1
#    #vibrancy = 0.5
#}


#label {
#    monitor =
#    text = hi, $USER
#    color = $font_color
#    font_size = 18
#    font_family = JetBrainsMonoNL Nerd Font
#    position = 0, -150
#    halign = center
#    valign = center
#
#}



animations {
    enabled = true
}


input-field {
    monitor =
    halign = center
    valign = center

    size = 250, 40
    position = 0, -25

    # Colors and Styles
    inner_color = $inner_color
    inner_opacity = 0.0
    outer_color = $outer_colors
    outline_thickness = 0

    font_family = JetBrainsMonoNL Nerd Font
    font_color = $font_color

    # --- THE MAGIC SETTINGS ---
    fade_on_empty = true
    fade_timeout = 1000 # Milliseconds before it fades out after clearing
    placeholder_text =  # Leave empty so nothing shows when hidden
    # --------------------------

    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 999
    shadow_passes = 0
}

auth {
    fingerprint:enabled = true
}
