
# Basic colors
foreground #d1d7d5
background #1a0f0a

# Cursor
cursor #d1d7d5
cursor_text_color #d1d7d5

# Selection
selection_foreground #1a0f0a
selection_background #d1d7d5

# Tab bar colors
tab_bar_background #d1d7d5
active_tab_foreground #d1d7d5
active_tab_background #526E95
inactive_tab_foreground #929695
inactive_tab_background #d1d7d5

# Colors
color0  #1a0f0a
color1  #9E5B36
color2  #D4A268
color3  #3A5887
color4  #526E95
color5  #867B86
color6  #6D90AD
color7  #d1d7d5
color8  #929695
color9  #9E5B36
color10 #D4A268
color11 #3A5887
color12 #526E95
color13 #867B86
color14 #6D90AD
color15 #d1d7d5


