# Basic colors
foreground #242424
background #d0d0c8

# Cursor
cursor #242424
cursor_text_color #d0d0c8

# Selection
selection_foreground #242424
selection_background #db0030

# Tab bar colors
tab_bar_background #d0d0c8
active_tab_foreground #242424
active_tab_background #DE6A41
inactive_tab_foreground #494a42
inactive_tab_background #d0d0c8

# Colors
color0  #d0d0c8
color1  #db0030
color2  #2e3125
color3  #51573b
color4  #DE6A41
color5  #43432b
color6  #363a34
color7  #383835
color8  #494a42
color9  #ef597a
color10 #7a846a
color11 #a2a87c
color12 #e88b5f
color13 #a8a67b
color14 #777b6f
color15 #242424
